### ISSUE TITLE
sbctl requires root to run: mkdir /var/lib/sbctl: permission denied

### ISSUE THREAD

**Issue by aimaniskndar** [Foxboron/sbctl#339]
Hey everyone,

upon trying to run the command:

`sbctl create-keys`

I been greeted with the error of:

`sbctl requires root to run: mkdir /var/lib/sbctl: permission denied`

This error still exist despite I run `sudo` or `su` to change to root.

Here are my `bootctl status` result:

```
systemd-boot not installed in ESP.
No default/fallback boot loader installed in ESP.
System:
      Firmware: n/a (n/a)
 Firmware Arch: x64
   Secure Boot: disabled (setup)
  TPM2 Support: yes
  Measured UKI: no
  Boot into FW: supported

Current Boot Loader:
      Product: GRUB 2.12
     Features: ✗ Boot counting
               ✗ Menu timeout control
               ✗ One-shot menu timeout control
               ✗ Default entry control
               ✗ One-shot entry control
               ✗ Support for XBOOTLDR partition
               ✗ Support for passing random seed to OS
               ✗ Load drop-in drivers
               ✗ Support Type #1 sort-key field
               ✗ Support @saved pseudo-entry
               ✗ Support Type #1 devicetree field
               ✗ Enroll SecureBoot keys
               ✗ Retain SHIM protocols
               ✗ Menu can be disabled
               ✓ Boot loader sets ESP information

...skipping 1 line
         File: └─n/a

Random Seed:
 System Token: not set
       Exists: no

Available Boot Loaders on ESP:
          ESP: /boot (/dev/disk/by-partuuid/a2af45ac-f0b4-4f25-ba63-e51e597544c9)

Boot Loaders Listed in EFI Variables:
        Title: Windows Boot Manager
           ID: 0x0001
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/c40fc77f-44ae-41fb-8d57-fcf331bcf7cf
         File: └─/EFI/Microsoft/Boot/bootmgfw.efi

        Title: GRUB
           ID: 0x0002
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/a2af45ac-f0b4-4f25-ba63-e51e597544c9
         File: └─/EFI/GRUB/grubx64.efi

Boot Loader Entries:
        $BOOT: /boot (/dev/disk/by-partuuid/a2af45ac-f0b4-4f25-ba63-e51e597544c9)
        token: arch

0 entries, no entry could be determined as default.
```

and `sbctl status` print:

```
Installed:      ✗ sbctl is not installed
Setup Mode:     ✗ Enabled
Secure Boot:    ✗ Disabled
Vendor Keys:    none
```

**Comment by Foxboron** [comment]
It should work if you disable landlock with `--disable-landlock`. The underlying issue was fixed with https://github.com/Foxboron/sbctl/commit/61f918052d1c22bf610ffdae033470f390015fef

**Comment by aimaniskndar** [comment]
> It should work if you disable landlock with `--disable-landlock`. The underlying issue was fixed with [61f9180](https://github.com/Foxboron/sbctl/commit/61f918052d1c22bf610ffdae033470f390015fef)

I tried using the following options `sbctl --disable-landlock create-keys` and `sbctl create-keys --disable-landlock` but the result was still the same.
